### ISSUE TITLE
2023 年 2 月 17 日停机维护安排 + 2023 年 3 月 Vlab 资源回收计划

### ISSUE THREAD

**Issue by iBug** [USTC-vlab/notifications#12]
Vlab 平台计划于 2 月 17 日（星期五）14:00 - 17:00 进行停机维护，届时所有虚拟机将会关机，请大家合理安排使用时间。维护内容：平台功能与安全升级。

另外，我们计划于下个月初（3 月 1 日之后）对长期不活跃及离校用户的资源进行回收。上次**有效登录**虚拟机管理平台的时间在 2022 年 8 月 31 日或以前的用户（即 6 个月内从未登录平台或已离校），我们将不再保留其虚拟机等用户数据。想要保留数据继续使用 Vlab 服务的**在校用户**，可在本月内通过统一身份认证登录一次虚拟机管理平台。

关于「有效登录」和用户在校状态的判断，请参见 Vlab 文档中[查看用户信息][1]一节的说明。

  [1]: https://vlab.ustc.edu.cn/docs/web/#userinfo

**Comment by taoky** [comment]
2 月 17 日维护已完成。
